package Vista;

import Logica.Conector;
import Logica.Conexion;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Hekutoru
 */
public final class Opciones extends javax.swing.JInternalFrame {

    private Conector conector = Conector.getInstance();
    private Conexion conexion = Conexion.getInstance();
    private String servidor;
    private String usuario;
    private String clave;
    private String driver;
    private String service;
    private String servidorInicial;
    private String usuarioInicial;
    private String claveInicial;
    private String driverInicial;
    private String serviceInicial;

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        try {
            conector.cargarConfig();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "No fue posible cargar la configuración.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
        bajarDatos();
        ponerDatos();
        guardarDatos();
        //Cerrar.setEnabled(!conexion.getEstado());
    }

    public void bajarDatos() {
        servidor = conector.getServidor();
        usuario = conector.getUsuario();
        clave = conector.getClave();
        driver = conector.getDriver();
        service = conector.getService();
    }

    public void ponerDatos() {
        Servidor.setText(servidor);
        Usuario.setText(usuario);
        Clave.setText(clave);
        Driver.setText(driver);
        Publicador.setText(service);
    }

    public void sacarDatos() {
        servidor = Servidor.getText();
        usuario = Usuario.getText();
        clave = String.copyValueOf(Clave.getPassword());
        driver = Driver.getText();
        service = Publicador.getText();
    }

    public void guardarDatos() {
        servidorInicial = Servidor.getText();
        usuarioInicial = Usuario.getText();
        claveInicial = String.copyValueOf(Clave.getPassword());
        driverInicial = Driver.getText();
        serviceInicial = Publicador.getText();
    }

    public void subirDatos() {
        conector.setServidor(servidor);
        conector.setUsuario(usuario);
        conector.setClave(clave);
        conector.setDriver(driver);
        conector.setService(service);
    }

    public void recuperarDatos() {
        conector.setServidor(servidorInicial);
        conector.setUsuario(usuarioInicial);
        conector.setClave(claveInicial);
        conector.setDriver(driverInicial);
        conector.setService(serviceInicial);
    }

    public void imprimirDatos() {
        System.out.println(servidor);
        System.out.println(usuario);
        System.out.println(clave);
        System.out.println(driver);
        System.out.println(service);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aplicar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Opciones = new javax.swing.JTabbedPane();
        PanelConexion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Servidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Clave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        Driver = new javax.swing.JTextField();
        Probar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Publicador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Visitar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Revertir = new javax.swing.JButton();

        Aplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/edit-icon.png"))); // NOI18N
        Aplicar.setText("Aplicar");
        Aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarActionPerformed(evt);
            }
        });

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/delete-icon.png"))); // NOI18N
        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        setTitle("Opciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/options-icon.png"))); // NOI18N

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancel-icon.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/check-icon.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Servidor:");

        Servidor.setText("jdbc:mysql://localhost:3306/help4traveling?autoReconnect=true&useSSL=false");

        jLabel2.setText("Usuario:");

        Usuario.setText("root");

        jLabel3.setText("Clave:");

        Clave.setText("root");

        jLabel4.setText("Driver:");

        Driver.setText("com.mysql.jdbc.Driver");

        Probar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/db-icon.png"))); // NOI18N
        Probar.setText("Probar");
        Probar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProbarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConexionLayout = new javax.swing.GroupLayout(PanelConexion);
        PanelConexion.setLayout(PanelConexionLayout);
        PanelConexionLayout.setHorizontalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConexionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuario)
                            .addComponent(Servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(Clave)
                            .addComponent(Driver, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConexionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Probar)))
                .addContainerGap())
        );
        PanelConexionLayout.setVerticalGroup(
            PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Probar)
                .addContainerGap())
        );

        Opciones.addTab("Base de Datos", PanelConexion);

        Publicador.setText("http://localhost:9128/publicador");
        Publicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicadorActionPerformed(evt);
            }
        });

        jLabel5.setText("Publicador:");

        Visitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/globe-icon.png"))); // NOI18N
        Visitar.setText("Visitar");
        Visitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Publicador, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Visitar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Visitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Opciones.addTab("Web Services", jPanel1);

        Revertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/undo-icon.png"))); // NOI18N
        Revertir.setText("Revertir");
        Revertir.setToolTipText("");
        Revertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Opciones)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Revertir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Guardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Cancelar)
                    .addComponent(Revertir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        recuperarDatos();
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        sacarDatos();
        subirDatos();
        try {
            conector.salvarConfig();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "No fue posible guardar la configuración.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
        this.dispose();
    }//GEN-LAST:event_GuardarActionPerformed

    private void ProbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProbarActionPerformed
        sacarDatos();
        subirDatos();
        if (conexion.probarConexion()) {
            JOptionPane.showMessageDialog(null,
                    "Conexión probada exitosamente.",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        //Principal.desconectarMenu.setEnabled(true);
        //Cerrar.setEnabled(true);
    }//GEN-LAST:event_ProbarActionPerformed

    private void RevertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevertirActionPerformed
        conector.revertir();
        bajarDatos();
        ponerDatos();
        //imprimirDatos();
    }//GEN-LAST:event_RevertirActionPerformed

    private void AplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarActionPerformed
        sacarDatos();
        subirDatos();
        //imprimirDatos();
    }//GEN-LAST:event_AplicarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        conexion.cerrarConexion();
        //Cerrar.setEnabled(false);
        //System.out.println("Conexión cerrada.");
    }//GEN-LAST:event_CerrarActionPerformed

    private void PublicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublicadorActionPerformed

    private void VisitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitarActionPerformed
        try {
            Desktop.getDesktop().browse(new URL(service + "?wsdl").toURI());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    "No fue posible desplegar el vínculo.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_VisitarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aplicar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cerrar;
    private javax.swing.JPasswordField Clave;
    private javax.swing.JTextField Driver;
    private javax.swing.JButton Guardar;
    public javax.swing.JTabbedPane Opciones;
    private javax.swing.JPanel PanelConexion;
    private javax.swing.JButton Probar;
    private javax.swing.JTextField Publicador;
    private javax.swing.JButton Revertir;
    private javax.swing.JTextField Servidor;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton Visitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
